import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const matrixDots = localFont({
  fallback: ["monospace"],
  variable: "--font-matrix-dots",
  src: [
    {
      path: "../static/fonts/MatrixDots/MatrixDots.ttf",
      weight: "400",
      style: "normal",
    },
  ],
});

const system = localFont({
  fallback: ["sans-serif"],
  variable: "--font-system",
  src: [
    {
      path: "../static/fonts/System/System-bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../static/fonts/System/System-medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../static/fonts/System/System-regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../static/fonts/System/System-light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../static/fonts/System/System-thin.woff2",
      weight: "100",
      style: "normal",
    },
  ],
});

const fonts = [system.variable, matrixDots.variable].join(" ");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        type: "image/png",
        url: "/icon?<generated>",
        href: "/icon?<generated>",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fonts}>{children}</body>
    </html>
  );
}
